const Filt = [
    {
        id: '1',
        name: 'Large Format Printing',
        description: 'Mork Impression is a leading provider of large format printing services. We offer a wide range of large format print solutions, including banners, posters, signs, and more. We use the latest printing technology to ensure that our large format prints are of the highest quality. ',
        img1: 'template/img/service/Large/3.jpg',
        img2: 'template/img/service/Lfp.png ',
        img3: 'template/img/service/Large/2.jpg',
        // img4: 'template/img/service/Large/1.jpg',
    },
    {
        id: '2',
        name: 'Industrial & CommerPrintcial ',
        description: ' We print product descriptions for packaging, catalogs, safety instructions for machinery and manuals.  Our printers produce clean, concise and clear text for easy reading.',
        img1: 'template/img/service/ICprint/1.jpg',
        img2: 'template/img/service/Icp.png',
        img3: 'template/img/service/ICprint/2.jpg',
        img4: 'template/img/service/ICprint/3.jpg',
    },
    {
        id: '3',
        name: 'Industrial Lamination',
        description: ' Are you looking to create durable signs, transportation materials, billboards, parts and components for a variety of machines and equipment with a strong, durable, and versatile lamination solution, then our Industrial Lamination is the perfect option for you.',
        img1: 'template/img/service/Lmtn.png',
        img2: 'template/img/service/Lam/1.jpg',
        img3: 'template/img/service/Lam/2.jpg',
        img4: 'template/img/service/Lam/3.jpg',
    },
    {
        id: '4',
        name: 'Digital Colour Press',
        description: ' We offer printing solution that is fast, accurate, versatile, and cost-effective to produce high-quality color prints.        ',
        img1: 'template/img/service/Color/1.jpg',
        img2: 'template/img/service/Cp.png',
        img3: 'template/img/service/Color/2.jpg',
        img4: 'template/img/service/Color/3.jpg',
    },
    {
        id: '5',
        name: 'Graphic Design',
        description: 'Graphic design is a creative field that requires a strong understanding of visual principles, typography, and color theory. At Mork Impression, our professional team of designers produces creative, innovative and communicative designs for your events and prints.',
        img1: 'template/img/service/Design/1.jpg',
        img2: 'template/img/service/direct.jpg',
        img3: 'template/img/service/Design/2.png',
        img4: 'template/img/service/Design/3.jpg',
    },
    {
        id: '6',
        name: 'Colour Separation',
        description: 'Mork impression prints full-colour and high quality images using colour separation.',
        img1: 'template/img/service/cala.jpg',
        img2: 'template/img/service/Sep/1.jpg',
        img3: 'template/img/service/Sep/2.jpg',
        img4: 'template/img/service/Sep/3.jpg',
    },
    {
        id: '7',
        name: 'Offset Press',
        description: 'We use wide range of materials in a variety of colors and in high volumes to print books, magazines, newspapers, packaging, and posters of good and high quality standard.',
        img1: 'template/img/service/Op.png',
        img2: 'template/img/service/Press/1.jpg',
        img3: 'template/img/service/Press/2.jpg',
        img4: 'template/img/service/Press/3.jpg',
    },
    {
        id: '8',
        name: 'Security Printing',
        description: 'Are you looking to own watermarks, microprinting, security threads, optically variable inks Cheques, passports, security tapes, stock certificates, postage stamps and identity cards. We, at Mork Impression are experts in printing documents and items with features that make them difficult to counterfeit.',
        img1: 'template/img/service/Security/2.jpg',
        img2: 'template/img/service/Security/1.jpg',
        img3: 'template/img/service/sp.png',
        img4: 'template/img/service/Security/3.jpg',
    },

]
export default Filt;